### ISSUE TITLE
Логика приложения

### ISSUE THREAD

**Issue by coursar** [dilyarakhabibullina/SportmasterTryingTests#3]
https://github.com/dilyarakhabibullina/SportmasterTryingTests/blob/a0d41bc6f019be078ba48aa03c3c45cec0841200/src/main/java/ru/itpark/Sportmaster.java#L8-L10

1. currentPurchase должен быть входным параметром (аргументом метода)
2. Бонусы рассчитываются по другой формуле

**Comment by dilyarakhabibullina** [comment]
Да, на тот момент у меня не получился правильный код для расчета бонусов спортмастер, мы его доделали на уроке. На днях выложу уже верный, с бейджами Трависа.
